exec $mako
exec $bar

exec_always fcitx5
exec_always --no-startup-id wl-paste --watch cliphist store
exec hellwal --theme $(cat ~/.cache/hellwal/last-theme)

set $qt_platformtheme qt6ct

exec_always dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec_always --no-startup-id systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec_always swaybg -i ~/.config/themes/current/wallpaper.png -m fill
