set $mod Mod4

set $left h
set $down j
set $up k
set $right l

set $term alacritty
set $menu wofi
set $bar waybar
set $mako mako
set $locker swaylock

for_window [app_id="imv"] floating enable, move position center
for_window [app_id="mpv"] floating enable, move position center
for_window [app_id="tauonmb"] floating enable, move position center

for_window [title="wifi-manager"] floating enable, resize set 900 600, move position center, border pixel 2
for_window [title="bluetooth-manager"] floating enable, resize set 900 600, move position center, border pixel 2
