include ~/.cache/hellwal/kitty-colors.conf

font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        9

window_padding_width 12
hide_window_decorations yes

confirm_os_window_close 0

term xterm-256color
